name: Pull v2rayA latest to winget

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run PR
        shell: pwsh
        id: prep
        env:
          REF: ${{ github.ref }}
        run: |
          iwr https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
          $Installer_x64_url = "https://github.com/v2rayA/v2rayA/releases/download/v2.0.2/installer_windows_inno_x64_2.0.2.exe"
          $Installer_ARM64_url = "https://github.com/v2rayA/v2rayA/releases/download/v2.0.2/installer_windows_inno_arm64_2.0.2.exe"
          ./wingetcreate.exe update v2rayA.v2rayA --urls $Installer_x64_url $Installer_ARM64_url --version 2.0.2 --submit
